### ISSUE TITLE
JWT Token

### ISSUE THREAD

**Issue by scoobie** [joshuaslate/mkrn-starter#4]
Hi Josh It sounds like a stupid question, but how do you pass the token on your GET method. In postman i am trying to pass on the header   key:Authorization    value:Bearer MyToken.
Sorry to send this as a ticket , even if it´s not one

**Comment by joshuaslate** [comment]
Hi. Pass the header: { Authorization: JWT ey blah blah blah }.

You don't need to include "Bearer", just include the JWT sent back from the login, with "JWT" prepended.

Thanks,

Josh
