### ISSUE TITLE
User PUT method

### ISSUE THREAD

**Issue by scoobie** [joshuaslate/mkrn-starter#6]
Hi Josh, sorry to disturb you again,
On you PUT endpoint **_(/user/:id)_**, I am passing the id on the path, the Token on the HEADER and a  JSON object with the fields i want to update on the BODY.
It s giving me a 404 error and checking inside **_"exports.editUser"_** the constant _**safeData**_ is always undefined because of _**ctx.Body**_ is undefined too. How are you passing the fields to be updated?

**Comment by joshuaslate** [comment]
Sorry, silly mistake. I got this fixed. I hope to find time to put some work into improving the quality of this project soon. I've just been so busy!
